### ISSUE TITLE
Remove spaces in HEX payload / decoder on insert

### ISSUE THREAD

**Issue by tjvandam** [SmartParksOrg/smartparks-toolset#1]
When pasting a HEX payload string into the payload field, it would be most optimal to remove any spaces when present.

Example:

3C0000013C0000000000C8003C00023205020005

versus:

3C 00 00 01 3C 00 00 00 00 00 C8 00 3C 00 02 32 05 02 00 05

**Comment by adminfriso** [comment]
resolved in #89e3c3f5d2553a13a77f1961e56894b5f1b02c66
